meta_product_name: "Douglas Berkley"
meta_title: "Douglas Berkley - Web Developer Profile"
meta_description: "Check out all of the latest projects from douglasberkley.com"
meta_image: "facebook-card.jpg"
